ALTER TABLE user_documents
  ADD COLUMN IF NOT EXISTS file_url VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS mime_type VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS stored_name VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS file_size_bytes BIGINT NULL,
  ADD COLUMN IF NOT EXISTS file_hash VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS document_type VARCHAR(60) NOT NULL DEFAULT 'other',
  ADD COLUMN IF NOT EXISTS storage_scope VARCHAR(30) NOT NULL DEFAULT 'vault';

ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS document_vault_pin_hash VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS document_vault_pin_updated_at TIMESTAMP NULL DEFAULT NULL;
