CREATE TABLE IF NOT EXISTS user_profiles (
  user_id INT NOT NULL,
  dob DATE NULL,
  gender VARCHAR(20) NULL,
  country VARCHAR(100) NULL,
  nationality VARCHAR(100) NULL,
  city VARCHAR(100) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_user_profiles_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
);
