ALTER TABLE universities
  ADD COLUMN IF NOT EXISTS overview TEXT NULL,
  ADD COLUMN IF NOT EXISTS courses TEXT NULL,
  ADD COLUMN IF NOT EXISTS fees TEXT NULL,
  ADD COLUMN IF NOT EXISTS facilities TEXT NULL,
  ADD COLUMN IF NOT EXISTS scholarships TEXT NULL,
  ADD COLUMN IF NOT EXISTS admissions TEXT NULL,
  ADD COLUMN IF NOT EXISTS location VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS contact VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS image_url VARCHAR(255) NULL;
